In [1]:
#1-casring tuple in 1-d array
my_list=[1,2,3]
import numpy as np

In [2]:
arr=np.array(my_list)

In [3]:
arr

array([1, 2, 3])

In [5]:
#2-casting of 2-d array
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#3-using arange and zeros and ones
Note-->(())double in case of matrix
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [17]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [20]:
np.zeros([3,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
np.ones(2)

array([ 1.,  1.])

In [22]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
#Linspace for equal number of spaces
np.linspace(0,5,11)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [24]:
#identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [27]:
#To input Random number 
np.random.rand(5,3)

array([[ 0.36183838,  0.33847726,  0.40275472],
       [ 0.86980052,  0.53376869,  0.37098681],
       [ 0.51398621,  0.98128668,  0.87276832],
       [ 0.61656868,  0.54333962,  0.98372682],
       [ 0.1996351 ,  0.75368031,  0.02553577]])

In [30]:
np.random.randn(5,3)

array([[ 0.7760357 , -1.85728275, -0.27348189],
       [-0.21742452, -0.79257416,  1.43909205],
       [ 0.50544229, -1.69719377, -0.19365969],
       [-0.1239732 ,  0.01549924,  0.81042965],
       [-0.65661377,  1.59121939, -0.35068605]])

In [31]:
np.random.randint(1,100,10)

array([42, 77, 85, 38, 90,  6, 35, 65, 21, 66])

In [36]:
#using of Reshape method
arr=np.arange(25)

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ran=np.random.randint(0,50,10)

In [41]:
ran

array([35, 48, 37, 39, 33, 45, 44, 14, 14, 26])

In [42]:
ran.max()

48

In [43]:
ran.min()

14

In [44]:
ran.argmax()

1

In [45]:
ran.argmin()

7

In [46]:
arr.dtype

dtype('int32')

In [48]:
#Selection
arr=np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[8]

8

In [52]:
arr[1:5]

array([1, 2, 3, 4])

In [53]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [54]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
slice=arr[0:6]

In [60]:
slice

array([0, 1, 2, 3, 4, 5])

In [61]:
slice[:]=99

In [62]:
slice

array([99, 99, 99, 99, 99, 99])

In [63]:
arr #defecting the orignal array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
#therefore copying
arr_copy=arr.copy()

In [65]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
sel=np.array(mat)

In [75]:
sel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
sel[0,0]

1

In [77]:
sel[2,2]

9

In [78]:
sel[:2,1:]

array([[2, 3],
       [5, 6]])

In [81]:
#conditional Select
ar=np.arange(0,11)

In [82]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
bool_ar=ar>5

In [85]:
bool_ar

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [86]:
ar[ar>5]

array([ 6,  7,  8,  9, 10])

In [87]:
ar[ar<3]

array([0, 1, 2])

In [88]:
ar_2d=np.arange(50).reshape(5,10)

In [89]:
ar_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [91]:
ar_2d[2:4,3:6]

array([[23, 24, 25],
       [33, 34, 35]])